create table buddy (clothes_id bigint not null, color_id bigint not null, created_at TIMESTAMPTZ not null, hair_style_id bigint not null, id bigint generated by default as identity, updated_at TIMESTAMPTZ not null, user_id bigint not null unique, name TEXT not null, nickname TEXT not null, primary key (id));
create table diary (date date not null, id integer generated by default as identity, user_id bigint not null, body TEXT not null, title varchar(255) not null, primary key (id));
create table taak_task (id integer generated by default as identity, is_all_day boolean not null, load_score integer not null, completed_at timestamp(6), due_at timestamp(6) not null, user_id bigint not null, memo TEXT not null, title varchar(255) not null, primary key (id));
create table taak_user (id bigint generated by default as identity, line_sub varchar(255) unique, password varchar(255), username varchar(255) unique, primary key (id));
create table taak_user_roles (taak_user_id bigint not null, roles varchar(255));
alter table if exists buddy add constraint FKly0o9pktdliup3rcudpeyvwho foreign key (user_id) references taak_user;
alter table if exists diary add constraint FKicd4egl46ha9186c3qi4f7kh7 foreign key (user_id) references taak_user;
alter table if exists taak_task add constraint FKnx44vkinsf3rvymxg6em30dp9 foreign key (user_id) references taak_user;
alter table if exists taak_user_roles add constraint FKoahoj7by44rbh3ke1txr22udo foreign key (taak_user_id) references taak_user;
