create table taak_user (id bigint generated by default as identity, line_sub varchar(255) unique, nick_name varchar(255), password varchar(255), username varchar(255) unique, primary key (id));
create table taak_user_roles (taak_user_id bigint not null, roles varchar(255));
alter table if exists taak_user_roles add constraint FKoahoj7by44rbh3ke1txr22udo foreign key (taak_user_id) references taak_user;
