create table diary (date date not null, id integer generated by default as identity, user_id bigint not null, body TEXT not null, title varchar(255) not null, primary key (id));
create table taak_user (id bigint generated by default as identity, line_sub varchar(255) unique, nick_name varchar(255), password varchar(255), username varchar(255) unique, primary key (id));
create table taak_user_roles (taak_user_id bigint not null, roles varchar(255));
alter table if exists diary add constraint FKicd4egl46ha9186c3qi4f7kh7 foreign key (user_id) references taak_user;
alter table if exists taak_user_roles add constraint FKoahoj7by44rbh3ke1txr22udo foreign key (taak_user_id) references taak_user;
