/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/routes/__root'
import { Route as AuthImport } from './app/routes/_auth'
import { Route as AppImport } from './app/routes/_app'
import { Route as IndexImport } from './app/routes/index'
import { Route as AuthLoginImport } from './app/routes/_auth/login'
import { Route as AppTabTopPagesImport } from './app/routes/_app/_tab-top-pages'
import { Route as AppDiaryNewImport } from './app/routes/_app/diary/new'
import { Route as AppTabTopPagesTodoImport } from './app/routes/_app/_tab-top-pages/todo'
import { Route as AppTabTopPagesDiaryImport } from './app/routes/_app/_tab-top-pages/diary'
import { Route as AppTabTopPagesDashboardImport } from './app/routes/_app/_tab-top-pages/dashboard'
import { Route as AppTabTopPagesBuddyImport } from './app/routes/_app/_tab-top-pages/buddy'
import { Route as AppTabTopPagesAccountImport } from './app/routes/_app/_tab-top-pages/account'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AppTabTopPagesRoute = AppTabTopPagesImport.update({
  id: '/_tab-top-pages',
  getParentRoute: () => AppRoute,
} as any)

const AppDiaryNewRoute = AppDiaryNewImport.update({
  id: '/diary/new',
  path: '/diary/new',
  getParentRoute: () => AppRoute,
} as any)

const AppTabTopPagesTodoRoute = AppTabTopPagesTodoImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppTabTopPagesRoute,
} as any)

const AppTabTopPagesDiaryRoute = AppTabTopPagesDiaryImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppTabTopPagesRoute,
} as any)

const AppTabTopPagesDashboardRoute = AppTabTopPagesDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppTabTopPagesRoute,
} as any)

const AppTabTopPagesBuddyRoute = AppTabTopPagesBuddyImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => AppTabTopPagesRoute,
} as any)

const AppTabTopPagesAccountRoute = AppTabTopPagesAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppTabTopPagesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_app/_tab-top-pages': {
      id: '/_app/_tab-top-pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppTabTopPagesImport
      parentRoute: typeof AppImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_app/_tab-top-pages/account': {
      id: '/_app/_tab-top-pages/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppTabTopPagesAccountImport
      parentRoute: typeof AppTabTopPagesImport
    }
    '/_app/_tab-top-pages/buddy': {
      id: '/_app/_tab-top-pages/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof AppTabTopPagesBuddyImport
      parentRoute: typeof AppTabTopPagesImport
    }
    '/_app/_tab-top-pages/dashboard': {
      id: '/_app/_tab-top-pages/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppTabTopPagesDashboardImport
      parentRoute: typeof AppTabTopPagesImport
    }
    '/_app/_tab-top-pages/diary': {
      id: '/_app/_tab-top-pages/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppTabTopPagesDiaryImport
      parentRoute: typeof AppTabTopPagesImport
    }
    '/_app/_tab-top-pages/todo': {
      id: '/_app/_tab-top-pages/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof AppTabTopPagesTodoImport
      parentRoute: typeof AppTabTopPagesImport
    }
    '/_app/diary/new': {
      id: '/_app/diary/new'
      path: '/diary/new'
      fullPath: '/diary/new'
      preLoaderRoute: typeof AppDiaryNewImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppTabTopPagesRouteChildren {
  AppTabTopPagesAccountRoute: typeof AppTabTopPagesAccountRoute
  AppTabTopPagesBuddyRoute: typeof AppTabTopPagesBuddyRoute
  AppTabTopPagesDashboardRoute: typeof AppTabTopPagesDashboardRoute
  AppTabTopPagesDiaryRoute: typeof AppTabTopPagesDiaryRoute
  AppTabTopPagesTodoRoute: typeof AppTabTopPagesTodoRoute
}

const AppTabTopPagesRouteChildren: AppTabTopPagesRouteChildren = {
  AppTabTopPagesAccountRoute: AppTabTopPagesAccountRoute,
  AppTabTopPagesBuddyRoute: AppTabTopPagesBuddyRoute,
  AppTabTopPagesDashboardRoute: AppTabTopPagesDashboardRoute,
  AppTabTopPagesDiaryRoute: AppTabTopPagesDiaryRoute,
  AppTabTopPagesTodoRoute: AppTabTopPagesTodoRoute,
}

const AppTabTopPagesRouteWithChildren = AppTabTopPagesRoute._addFileChildren(
  AppTabTopPagesRouteChildren,
)

interface AppRouteChildren {
  AppTabTopPagesRoute: typeof AppTabTopPagesRouteWithChildren
  AppDiaryNewRoute: typeof AppDiaryNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTabTopPagesRoute: AppTabTopPagesRouteWithChildren,
  AppDiaryNewRoute: AppDiaryNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppTabTopPagesRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/account': typeof AppTabTopPagesAccountRoute
  '/buddy': typeof AppTabTopPagesBuddyRoute
  '/dashboard': typeof AppTabTopPagesDashboardRoute
  '/diary': typeof AppTabTopPagesDiaryRoute
  '/todo': typeof AppTabTopPagesTodoRoute
  '/diary/new': typeof AppDiaryNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppTabTopPagesRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/account': typeof AppTabTopPagesAccountRoute
  '/buddy': typeof AppTabTopPagesBuddyRoute
  '/dashboard': typeof AppTabTopPagesDashboardRoute
  '/diary': typeof AppTabTopPagesDiaryRoute
  '/todo': typeof AppTabTopPagesTodoRoute
  '/diary/new': typeof AppDiaryNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_tab-top-pages': typeof AppTabTopPagesRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/_tab-top-pages/account': typeof AppTabTopPagesAccountRoute
  '/_app/_tab-top-pages/buddy': typeof AppTabTopPagesBuddyRoute
  '/_app/_tab-top-pages/dashboard': typeof AppTabTopPagesDashboardRoute
  '/_app/_tab-top-pages/diary': typeof AppTabTopPagesDiaryRoute
  '/_app/_tab-top-pages/todo': typeof AppTabTopPagesTodoRoute
  '/_app/diary/new': typeof AppDiaryNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/account'
    | '/buddy'
    | '/dashboard'
    | '/diary'
    | '/todo'
    | '/diary/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/account'
    | '/buddy'
    | '/dashboard'
    | '/diary'
    | '/todo'
    | '/diary/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/_tab-top-pages'
    | '/_auth/login'
    | '/_app/_tab-top-pages/account'
    | '/_app/_tab-top-pages/buddy'
    | '/_app/_tab-top-pages/dashboard'
    | '/_app/_tab-top-pages/diary'
    | '/_app/_tab-top-pages/todo'
    | '/_app/diary/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_tab-top-pages",
        "/_app/diary/new"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login"
      ]
    },
    "/_app/_tab-top-pages": {
      "filePath": "_app/_tab-top-pages.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_tab-top-pages/account",
        "/_app/_tab-top-pages/buddy",
        "/_app/_tab-top-pages/dashboard",
        "/_app/_tab-top-pages/diary",
        "/_app/_tab-top-pages/todo"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_app/_tab-top-pages/account": {
      "filePath": "_app/_tab-top-pages/account.tsx",
      "parent": "/_app/_tab-top-pages"
    },
    "/_app/_tab-top-pages/buddy": {
      "filePath": "_app/_tab-top-pages/buddy.tsx",
      "parent": "/_app/_tab-top-pages"
    },
    "/_app/_tab-top-pages/dashboard": {
      "filePath": "_app/_tab-top-pages/dashboard.tsx",
      "parent": "/_app/_tab-top-pages"
    },
    "/_app/_tab-top-pages/diary": {
      "filePath": "_app/_tab-top-pages/diary.tsx",
      "parent": "/_app/_tab-top-pages"
    },
    "/_app/_tab-top-pages/todo": {
      "filePath": "_app/_tab-top-pages/todo.tsx",
      "parent": "/_app/_tab-top-pages"
    },
    "/_app/diary/new": {
      "filePath": "_app/diary/new.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
